name: Update Image Tag
on:
  # schedule:
  #   - cron: "29 10 1,5 * *"
  push:
    branches: ["master"]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: bash scripts/update_tag.sh
