name: Build n Push
run-name: Build images & push to Docker hub
on:
  push:
    branches: ["master"]
  schedule:
    - cron: "37 3 */2 * *"

jobs:
  update-build-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update app if it's not up to date
        run: bash ./scripts/update.sh

      - name: Set Qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: bash scripts/build.sh
